config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pledgeable#home'
  get 'home' => 'pledgeable#home'
  get 'charities' => 'pledgeable#charities'
  get 'mark_completed' => 'events#mark_completed'
  get 'user_profile' => 'pledgeable#user_profile'
  post '/webhook_events/:source', to: 'webhook_events#create'
  
      devise_for :charities, path: 'c', controllers: {
        sessions: 'charities/sessions',
        passwords: 'charities/passwords',
        registrations: 'charities/registrations'}
      resources :pledges
      devise_for :users, path: 'u', controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'}
      resources :events

  # Using checkout for saving users cards for now despite them not actually 'checking out'
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'pledgeable#home', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  scope '/account' do
    post 'create', to: 'account#create', as: 'account_create'
    post 'login', to: 'account#login', as: 'account_login'
    get 'reauth', to: 'pledgeable#home', as: 'account_reauth'
    get 'return', to: 'pledgeable#home', as: 'account_return'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :set_pledge, only: [:show, :edit, :update, :destroy]

  # GET /pledges
  # GET /pledges.json
  def index
    @pledges = Pledge.all
  end

  # GET /pledges/1
  # GET /pledges/1.json
  def show
  end

  # GET /pledges/new
  def new
    @pledge = Pledge.new
    @event = Event.find(params[:id])
  end

  # GET /pledges/1/edit
  def edit
  end

  # POST /pledges
  # POST /pledges.json
  def create
    @pledge = Pledge.new(pledge_params)   
    @pledge.user_id = current_user.id
    @event = Event.find_by(params[:id])

    respond_to do |format|
      if @pledge.save
        format.html { redirect_to @event, notice: 'Pledge was successfully created.' }
        format.json { render :show, status: :created, location: @pledge }
      else
        format.html { render :new }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pledges/1
  # PATCH/PUT /pledges/1.json
  def update
    respond_to do |format|
      if @pledge.update(pledge_params)
        format.html { redirect_to @pledge, notice: 'Pledge was successfully updated.' }
        format.json { render :show, status: :ok, location: @pledge }
      else
        format.html { render :edit }
        format.json { render json: @pledge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledges/1
  # DELETE /pledges/1.json
  def destroy
    @pledge.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Pledge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pledge
      @pledge = Pledge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pledge_params
      params.require(:pledge).permit(:amount, :max_amount, :user_id, :event_id)
    end
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/views/pledges/_form.html.erb
<div class="row pt-3 pb-5">
  <div class="col-sm-8 offset-sm-2">

    <%= form_with(model: pledge, local: true) do |form| %>
      <% if pledge.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

          <ul>
            <% pledge.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="text-center">
        <h3>for</h3>
        <h3><%= @event.name %></h3>
        <h3>by:</h3>
        <h3><%= @event.user.username %></h3>
    </div>

      <div class="form-group pt-5 pb-5">
        <%= form.number_field :amount, :step => 0.01, placeholder: "Pledge Amount", class: "form-control form-control-lg" %>
      </div>

      <div class="form-group pb-5">
        <%= form.number_field :max_amount, step: :any, placeholder: "Maximum Donation Amount(optional)", class: "form-control form-control-lg"%>
      </div>

      <%= form.hidden_field :event_id, value: @event.id %>

      <div class="actions text-center">
        <%= form.submit %>
      </div>
    <% end %>

  </div>
</div>

app/views/pledges/edit.html.erb
<h1>Editing Pledge</h1>

<%= render 'form', pledge: @pledge %>

<%= link_to 'Show', @pledge %> |
<%= link_to 'Back', pledges_path %>

app/views/pledges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pledges</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Max amount</th>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pledges.each do |pledge| %>
      <tr>
        <td><%= pledge.amount %></td>
        <td><%= pledge.max_amount %></td>
        <td><%= pledge.user_id %></td>
        <td><%= pledge.event_id %></td>
        <td><%= link_to 'Show', pledge %></td>
        <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
        <td><%= link_to 'Destroy', pledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pledge', new_pledge_path %>

app/views/pledges/new.html.erb
<h2>New Pledge</h2>

<%= render 'form', pledge: @pledge %>

app/views/pledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @pledge.amount %>
</p>

<p>
  <strong>Max amount:</strong>
  <%= @pledge.max_amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @pledge.user_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @pledge.event_id %>
</p>

<%= link_to 'Edit', edit_pledge_path(@pledge) %> |
<%= link_to 'Back', pledges_path %>