config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pledgeable#home'
  get 'home' => 'pledgeable#home'
  get 'charities' => 'pledgeable#charities'
  get 'mark_completed' => 'events#mark_completed'
  get 'user_profile' => 'pledgeable#user_profile'
  post '/webhook_events/:source', to: 'webhook_events#create'
  
      devise_for :charities, path: 'c', controllers: {
        sessions: 'charities/sessions',
        passwords: 'charities/passwords',
        registrations: 'charities/registrations'}
      resources :pledges
      devise_for :users, path: 'u', controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'}
      resources :events

  # Using checkout for saving users cards for now despite them not actually 'checking out'
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'pledgeable#home', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  scope '/account' do
    post 'create', to: 'account#create', as: 'account_create'
    post 'login', to: 'account#login', as: 'account_login'
    get 'reauth', to: 'pledgeable#home', as: 'account_reauth'
    get 'return', to: 'pledgeable#home', as: 'account_return'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  after_save :stripe_auto_transfer, if: :saved_change_to_event_completed_on? 

  belongs_to :user
  belongs_to :charity, optional: true
  belongs_to :event_category, optional: true
  has_many :pledges

  def total_pledge_amount
    pledge_amount_arr = []
    self.pledges.each do |pledge|
      pledge_amount_arr.push(pledge.amount)
    end
    amount = pledge_amount_arr.sum
    return amount
  end

  private

    def stripe_auto_transfer    
      self.pledges.each do |pledge|

        product = Stripe::Product.create({
          name: pledge.user.email + 'donation' + pledge.id.to_s
        })
        
        if pledge.max_amount < (self.amount * pledge.amount)
          price = Stripe::Price.create({
          product: product,
          unit_amount: (pledge.max_amount*100).to_i,
          currency: 'usd'
        })
        else
          price = Stripe::Price.create({
            product: product,
            unit_amount: ((self.amount * pledge.amount)*100).to_i,
            currency: 'usd'
          })
        end

        Stripe::InvoiceItem.create({
          customer: pledge.user.stripe_customer_id,
          price: price
        })

        invoice = Stripe::Invoice.create({
          customer: pledge.user.stripe_customer_id,
          collection_method: 'charge_automatically',
          auto_advance: true,
          transfer_data: {
            destination: pledge.event.charity.stripe_account_id,
            amount: ( price.unit_amount * 0.95 ).to_i
          }
        })

      end

    end

  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def mark_completed  
    @event = Event.find_by(params[:event])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end        
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :amount, :event_completed_on, :user_id, :charity_id, :event_category_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row pt-5 pb-5">
  <div class="col-sm-8 offset-sm-2">

    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>    

      <div class="form-group pt-2 pb-2">
        <%= form.text_field :name, placeholder: "Name", class: "form-control form-control-lg" %>
      </div>

      <div class="form-group pt-2 pb-2">          
        <%= form.text_area :description, placeholder: "Describe your event", class: "form-control form-control-lg", rows: "5" %>
      </div> 

      <%= form.collection_select(:event_category_id, EventCategory.all, :id, :name, { :prompt => 'Select your event type' }, class: "form-select form-select-lg mb-3") %>  

      <%= form.collection_select(:charity_id, Charity.all, :id, :name, { :prompt => 'Select your charity' }, class: "form-select form-select-lg mb-3") %>

      <div class="actions pt-5 text-center">
        <%= form.submit %>
      </div>
    <% end %>

  </div>
</div>

app/views/events/_mark_completed_form.html.erb
<div class="row pt-5 pb-5">
  <div class="col-sm-8 offset-sm-2">

    <%= form_with(model: @event, local: true) do |form| %>
      <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% @event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>    

        <div class="form-group pt-2 pb-2">
          <%= form.number_field :amount, :step => 0.01, placeholder: "Amount", class: "form-control form-control-lg" %>
        </div>

        <div class="form-group pt-2 pb-2">          
          <%= form.datetime_local_field :event_completed_on, class: "form-control form-control-lg" %>
        </div>    

      <div class="actions pt-5 text-center">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/add_category.html.erb
<%= render 'events/forms/add_category_form', event: @event %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

  <% @events.each do |event| %>
    <div class="card">
      <div class="card-body">
        <h1><%= event.name %></h1>
        <p><%= event.description %></p>
        <%= link_to 'Show', event %>
        <%= link_to 'Mark as completed', edit_event_path(event) %>
        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to  "Pledge", new_pledge_path(id: event.id) %>
         <% event.pledges.each do |pledge| %>
          <div class="card">
            <div class="card-body">
            <p><%= pledge.user.email %> has pledged <%= number_to_currency(pledge.amount) %>          
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

<br>

<% if user_signed_in? %>
   <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<% end %>

<% if user_signed_in? %>
  <%= button_to 'Add card info', checkout_create_path, method: :post, params: {id: current_user.id}, remote: true %>
<% end %>

<%= link_to 'New Event', new_event_path %>

app/views/events/mark_completed.html.erb
<%= render 'mark_completed_form' %>

app/views/events/new.html.erb
<h2>New Event</h2>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">

    <div class="d-grid gap-2 pt-5 pb-5 col-6 mx-auto">   
      <%= link_to 'Home', root_path, class: "btn btn-lg btn-dark" %>
    </div>

    <div class="card border-dark">
      <div class="card-header">
        <h3><%= @event.name %></h3>
        <h4>Event created by: <%= @event.user.username %></h4>         
      </div>
      <div class="card-body">
        <h4><%= @event.description %></h4> 
      </div>
    </div>

    <div class="d-grid gap-2 pt-5 pb-5 col-6 mx-auto">
      <% if user_signed_in? && current_user.stripe_customer_id.present? %>
        <%= link_to  "Pledge", new_pledge_path(id: @event.id), class: "btn btn-success btn-lg mt-3 mb-3" %>
      <% end %>
    </div>   

    <div class="card border-dark mb-5">
      <div class="card-body">
        <h4 style="font-weight: bold; text-align:center">Total pledged per mile: <%= number_to_currency(@event.total_pledge_amount) %></h4>
      </div>
    </div>

    <% @event.pledges.each do |pledge| %>
      <div class="card border-dark mb-5">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-7">
            <% if user_signed_in? && current_user.id == pledge.user.id %>
              <h4> You have pledged: <%= number_to_currency(pledge.amount) %> </h4>
            <% else %>
              <h4><%= pledge.user.username %> has pledged: <%= number_to_currency(pledge.amount) %> </h4>  
            <% end %>
            </div>
            <div class="col-sm-5 text-center pt-3">
              <% if user_signed_in? && current_user.id == pledge.user.id %>
                <%= link_to "Remove", pledge, method: :delete, data: { confirm: 'Are you sure you want to remove your pledge?'}, class: 'btn btn-danger btn-sm'%>       
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <% if user_signed_in? && current_user.id == @event.user.id %>
      <% if @event.event_completed_on.blank? %>
            <div class="d-grid gap-2 pt-5 pb-5 col-6 mx-auto">
              <%= link_to 'Mark as completed', mark_completed_path(@event), class: "btn btn-lg btn-dark" %>
            </div>
            <div class="d-grid gap-2 pt-5 pb-5 col-6 mx-auto">
              <%= link_to 'Delete Event', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg" %>
            </div>
      <% end %>
    <% end %> 
    
  </div>
</div>
                  
 





    

       