config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pledgeable#home'
  get 'home' => 'pledgeable#home'
  get 'charities' => 'pledgeable#charities'
  get 'mark_completed' => 'events#mark_completed'
  get 'user_profile' => 'pledgeable#user_profile'
  post '/webhook_events/:source', to: 'webhook_events#create'
  
      devise_for :charities, path: 'c', controllers: {
        sessions: 'charities/sessions',
        passwords: 'charities/passwords',
        registrations: 'charities/registrations'}
      resources :pledges
      devise_for :users, path: 'u', controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'}
      resources :events

  # Using checkout for saving users cards for now despite them not actually 'checking out'
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'pledgeable#home', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  scope '/account' do
    post 'create', to: 'account#create', as: 'account_create'
    post 'login', to: 'account#login', as: 'account_login'
    get 'reauth', to: 'pledgeable#home', as: 'account_reauth'
    get 'return', to: 'pledgeable#home', as: 'account_return'

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/pledgeable_controller.rb
class PledgeableController < ApplicationController
  def home
    @events = Event.all
  end

  def charities
    @charities = Charity.all
  end

  def user_profile
    @user = User.find(params[:id])
  end
end

app/helpers/pledgeable_helper.rb
module PledgeableHelper
end

app/views/pledgeable/charities.html.erb
<% @charities.each do |charity| %>
  <div class="row">
    <div class="col-sm">
      <%= charity.name %>
    </div>
  </div>
<% end %>

app/views/pledgeable/home.html.erb
<p>Pledgeable is a web app that gives you the power to raise money for charity by creating and completing events.  Share your event with others who can pledge to your cause.</p>

<% if !user_signed_in? && !charity_signed_in? %>
  <div class="row pt-5 pb-5">
    <div class="col-sm pt-5 pb-5">
      <div class="d-grid gap-2">
        <%= link_to "USER LOG IN", new_user_session_path, class: "btn btn-dark btn-lg pt-5 pb-5 pl-5 pr-5" %>
      </div>
    </div>
  </div>

  <div class="row pt-5 pb-5">
    <div class="col-sm pt-5 pb-5">
      <div class="d-grid gap-2">
        <%= link_to "CHARITY LOG IN", new_charity_session_path, class: "btn btn-dark btn-lg pt-5 pb-5 pl-5 pr-5", type: "button" %>
      </div>
    </div>
  </div>
<% elsif charity_signed_in? && current_charity.stripe_account_id.blank? %> 
  <div class="d-grid gap-2">
    <%= link_to 'Connect with Stripe', account_create_path, method: :post, class: "btn btn-dark btn-lg mt-5" %>
  </div>
  <div class="d-grid gap-2">
    <%= link_to "Sign out", destroy_charity_session_path, method: :delete, class: "btn btn-dark btn-lg mt-5"  %>
  </div>
<% elsif charity_signed_in? %>
  <div class="d-grid gap-2">
    <%= link_to 'View Stripe Account', account_login_path, method: :post, remote: true, class: "btn btn-dark btn-lg mt-5" %>
  </div>
  <div class="d-grid gap-2">
    <%= link_to "Sign out", destroy_charity_session_path, method: :delete, class: "btn btn-dark btn-lg mt-5" %>
  </div>
<% else user_signed_in? %> 
  <% if current_user.stripe_customer_id.blank? %>
    <div class="row pt-5">
      <div class="col-sm-6 offset-sm-3">
        <div class="card">
          <h4>* Please add your card info in order to pledge to events.</h4>
        </div>
        <div class="d-grid gap-2">
          <%= link_to 'Add card info', checkout_create_path, method: :post, params: {id: current_user.id}, remote: true, class: "btn btn-dark btn-lg mt-5" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row pt-5">
    <div class="col-sm-6 offset-sm-3">
      <div class="d-grid gap-2">
        <%= link_to "New Event", new_event_path, class: "btn btn-dark btn-lg" %>
      </div>
    </div>
  </div>

  <div class="row pt-5 pb-5">
    <div class="col-sm-6 offset-sm-3 text-center">
      <div class="d-grid gap-2 pb-5">
        <%= link_to "Edit Profile", edit_user_registration_path(current_user), class: "btn btn-dark btn-lg" %>
      </div>
      <div class="d-grid gap-2">
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "btn btn-dark btn-lg" %>
      </div>
    </div>
  </div>

  <% @events.each do |event| %>
  <% if event.event_completed_on.blank? %>
    <div class="row pt-5">
      <div class="col-sm">
        <div class="card border border-dark">
          <div class="card-header bg-secondary">
            <h3><%= event.name %></h3>
            <% if user_signed_in? && current_user.id == event.user.id %>
              <h4>Event created by: You</h4>
            <% else %>
              <h4>Event created by: <%= link_to event.user.username, user_profile_path(id: event.user.id) %></h4>
            <% end %>
            <%= link_to 'View Event', event, class: "btn btn-dark btn-lg mt-3 mb-3" %>
          </div>
          <div class="card-body bg-light">
            <h4><%= event.description %></h4> 
          </div>
        </div>     
      </div>
    </div>  
  <% end %>
<% end %>


<% end %>
  

app/views/pledgeable/user_profile.html.erb
<div class="row pt-5 pb-5">
  <div class="col-sm-8 offset-sm-2 pb-5">
    <div class="card mb-3">
      <%= image_tag @user.avatar.variant(resize_to_limit: [150, nil]), class: "img-thumbnail card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= @user.username %></h5>
        <p class="card-text"><%= @user.email %></p>
        <p class="card-text"></p>
        <p class="card-text"></p>
      </div>
    </div>    
  </div>
</div>